/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-05-26 11:10:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import uts.isd.model.User;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1747989251484L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("uts.isd.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <title>Register - IoT Bay</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    class Header extends HTMLElement {\n");
      out.write("        connectedCallback() {\n");
      out.write("            const shadow = this.attachShadow({ mode: \"open\" });\n");
      out.write("            shadow.innerHTML = `\n");
      out.write("                <style>\n");
      out.write("                    .header {\n");
      out.write("                        display: flex;\n");
      out.write("                        justify-content: space-between;\n");
      out.write("                        align-items: center;\n");
      out.write("                        background-color: #333;\n");
      out.write("                        padding: 10px;\n");
      out.write("                        color: white;\n");
      out.write("                    }\n");
      out.write("                    .items {\n");
      out.write("                        list-style: none;\n");
      out.write("                        padding: 0;\n");
      out.write("                        display: flex;\n");
      out.write("                        gap: 15px;\n");
      out.write("                    }\n");
      out.write("                    .items a {\n");
      out.write("                        text-decoration: none;\n");
      out.write("                        color: white;\n");
      out.write("                        padding: 10px;\n");
      out.write("                        font-weight: bold;\n");
      out.write("                    }\n");
      out.write("                    .user-box {\n");
      out.write("                        display: flex;\n");
      out.write("                        gap: 10px;\n");
      out.write("                    }\n");
      out.write("                    .header-button {\n");
      out.write("                        background-color: transparent;\n");
      out.write("                        color: white;\n");
      out.write("                        font-weight: bold;\n");
      out.write("                        border: 2px solid white;\n");
      out.write("                        padding: 10px 30px;\n");
      out.write("                        cursor: pointer;\n");
      out.write("                        transition: 0.3s;\n");
      out.write("                    }\n");
      out.write("                    .header-button:hover {\n");
      out.write("                        background-color: white;\n");
      out.write("                        color: black;\n");
      out.write("                        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2);\n");
      out.write("                    }\n");
      out.write("                </style>\n");
      out.write("                <div class=\"header\">\n");
      out.write("                    <ul class=\"items\">\n");
      out.write("                        <li><a href=\"index.jsp\">HOME</a></li>\n");
      out.write("                        <li><a href=\"register.jsp\">REGISTER</a></li>\n");
      out.write("                        <li><a href=\"order?action=list\">🧾 MY ORDERS</a></li>\n");
      out.write("                        <li><a href=\"#\">ABOUT</a></li>\n");
      out.write("                        <li><a href=\"#\">CONTACT</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                    <div>\n");
      out.write("                        <h2>Logged in user:\n");
      out.write("                            ");

                                User loggedInUser = (User) session.getAttribute("user");
                                if (loggedInUser != null) {
                                    out.print(loggedInUser.getEmail());
                                } else {
                                    out.print("Guest");
                                }
                            
      out.write("\n");
      out.write("                        </h2>\n");
      out.write("                    </div>\n");
      out.write("                    ");
 if (session.getAttribute("user") != null) { 
      out.write("\n");
      out.write("                    <div class=\"user-box\">\n");
      out.write("                        <a href=\"profile-dashboard.jsp\"><button class=\"header-button\">My Info</button></a>\n");
      out.write("                        <a href=\"logout\"><button class=\"header-button\">LOGOUT</button></a>\n");
      out.write("                    </div>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("            `;\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    customElements.define(\"pref-header\", Header);\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<div class=\"register-form\">\n");
      out.write("  <h2>Register</h2>\n");
      out.write("  <form action=\"RegisterServlet\" method=\"post\">\n");
      out.write("    <label for=\"fullName\">Full Name:</label>\n");
      out.write("    <input id=\"fullName\" type=\"text\" name=\"fullName\" required><br><br>\n");
      out.write("\n");
      out.write("    <label for=\"email\">Email:</label>\n");
      out.write("    <input id=\"email\" type=\"email\" name=\"email\" required><br><br>\n");
      out.write("\n");
      out.write("    <label for=\"password\">Password:</label>\n");
      out.write("    <input id=\"password\" type=\"password\" name=\"password\" required><br><br>\n");
      out.write("\n");
      out.write("    <label for=\"dob\">Date of Birth:</label>\n");
      out.write("    <input id=\"dob\" type=\"date\" name=\"dob\" required><br><br>\n");
      out.write("\n");
      out.write("    <label for=\"gender\">Gender:</label>\n");
      out.write("    <select name=\"gender\" id=\"gender\" required>\n");
      out.write("      <option value=\"Male\">Male</option>\n");
      out.write("      <option value=\"Female\">Female</option>\n");
      out.write("      <option value=\"Other\">Other</option>\n");
      out.write("    </select><br><br>\n");
      out.write("\n");
      out.write("    <label for=\"role\">User Type:</label>\n");
      out.write("    <select name=\"role\" id=\"role\">\n");
      out.write("      <option value=\"CUSTOMER\">Customer</option>\n");
      out.write("      <option value=\"STAFF\">Staff</option>\n");
      out.write("    </select><br><br>\n");
      out.write("\n");
      out.write("    <label for=\"phone\">Phone Number:</label>\n");
      out.write("    <input type=\"text\" id=\"phone\" name=\"phone\" required><br><br>\n");
      out.write("\n");
      out.write("    <label for=\"tos\">Agree to our <span style=\"color: dodgerblue; cursor: pointer\">Terms of Service</span></label>\n");
      out.write("    <input type=\"checkbox\" id=\"tos\" name=\"tos\">\n");
      out.write("    <br>\n");
      out.write("    <input type=\"submit\" value=\"Register\">\n");
      out.write("  </form>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
