/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-05-21 13:19:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import uts.isd.model.User;

public final class userManagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("uts.isd.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <title>User Management</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"admin.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<h2>Create User</h2>\n");
 User currentUser = (User) session.getAttribute("loggedInUser");
  if (currentUser == null || !currentUser.isAdmin()) { 
      out.write("\n");
      out.write("<p style=\"color:red;\">You do not have permission to access this page.</p>\n");
      out.write("<a href=\"index.jsp\">Back to Home</a>\n");
 } else { 
      out.write("\n");
      out.write("<form action=\"AdminServlet\" method=\"post\">\n");
      out.write("  <input type=\"hidden\" name=\"action\" value=\"create\">\n");
      out.write("  <label>Name:</label>\n");
      out.write("  <input type=\"text\" name=\"name\" required><br>\n");
      out.write("  <label>Email:</label>\n");
      out.write("  <input type=\"email\" name=\"email\" required><br>\n");
      out.write("  <label>Password:</label>\n");
      out.write("  <input type=\"password\" name=\"password\" required><br>\n");
      out.write("  <label>Date of Birth:</label>\n");
      out.write("  <input type=\"date\" name=\"dob\"><br>\n");
      out.write("  <label>Gender:</label>\n");
      out.write("  <select name=\"gender\">\n");
      out.write("    <option value=\"Male\">Male</option>\n");
      out.write("    <option value=\"Female\">Female</option>\n");
      out.write("    <option value=\"Other\">Other</option>\n");
      out.write("  </select><br>\n");
      out.write("  <label>Phone Number:</label>\n");
      out.write("  <input type=\"text\" name=\"phoneNumber\"><br>\n");
      out.write("  <label>User Type:</label>\n");
      out.write("  <select name=\"userType\" required>\n");
      out.write("    <option value=\"CUSTOMER\">Customer</option>\n");
      out.write("    <option value=\"STAFF\">Staff</option>\n");
      out.write("    <!-- Uncomment if ADMIN creation is allowed -->\n");
      out.write("    <!-- <option value=\"ADMIN\">Admin</option> -->\n");
      out.write("  </select><br>\n");
      out.write("  <label>Is Active:</label>\n");
      out.write("  <input type=\"checkbox\" name=\"isActive\" checked><br>\n");
      out.write("  <button type=\"submit\">Create User</button>\n");
      out.write("</form>\n");
      out.write("<a href=\"index.jsp\">Back to Home</a>\n");
 } 
      out.write('\n');
 if (session.getAttribute("error") != null) { 
      out.write("\n");
      out.write("<p style=\"color:red;\">");
      out.print( session.getAttribute("error") );
      out.write("</p>\n");
 session.removeAttribute("error"); 
      out.write('\n');
 } 
      out.write('\n');
 if (session.getAttribute("success") != null) { 
      out.write("\n");
      out.write("<p style=\"color:green;\">");
      out.print( session.getAttribute("success") );
      out.write("</p>\n");
 session.removeAttribute("success"); 
      out.write('\n');
 } 
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
